name: TryHackMe Update Badge

on:
  schedule:
    - cron: '00 15 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          # Replace with your tryhackme username
          username: "revi1337"
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
